pipeline {
    agent any

    stages {

        stage('Git Checkout') {
            steps {
                git branch: 'main',
                    credentialsId: 'Github-Credentials',
                    url: 'https://github.com/ampymarcelo/TP002_CICD.git'
            }
        }

        stage('Build Application') {
            steps {
                bat 'docker run --rm -v %CD%:/app -w /app maven:latest mvn clean install -DskipTests'
            }
        }

        stage('Unit Tests') {
            steps {
                bat 'docker run --rm -v %CD%:/app -w /app maven:latest mvn test'
            }
        }

        stage('Build Docker Image') {
            steps {
                bat 'docker build -t ampy01/tp2-cicd:1.0.0 .'
            }
        }

        stage('Push to DockerHub') {
            steps {
                withCredentials([string(
                    credentialsId: 'dockerhubpass',
                    variable: 'dockerHubPass'
                )]) {
                    bat "docker login -u ampy01 -p %dockerHubPass%"
                    bat 'docker push ampy01/tp2-cicd:1.0.0'
                }
            }
        }
    }

    post {
        success {
            echo '✅ Pipeline terminé avec succès !'
        }
        failure {
            echo '❌ Pipeline échoué !'
        }
    }
}